#ifndef INTRO_HEADER_H
#define INTRO_HEADER_H

#include "types.h"

// geo
extern const GeoLayout intro_geo_0002D0[];
extern const GeoLayout intro_geo_mario_head_regular[];
extern const GeoLayout intro_geo_mario_head_dizzy[];
extern const GeoLayout intro_geo_000414[];

// leveldata
extern Lights0 logo_f3dlite_material_022_lights;
extern Lights1 logo_f3dlite_material_036_lights;
extern Lights0 logo_f3dlite_material_018_lights;
extern Lights0 logo_f3dlite_material_017_lights;
extern Lights0 logo_f3dlite_material_038_lights;
extern Lights0 logo_f3dlite_material_034_lights;
extern Lights0 logo_f3dlite_material_016_lights;
extern Lights0 logo_f3dlite_material_012_lights;
extern Lights0 logo_f3dlite_material_015_lights;
extern Lights0 logo_f3dlite_material_021_lights;
extern Lights0 logo_f3dlite_material_035_lights;
extern Lights0 logo_f3dlite_material_005_lights;
extern Lights0 logo_f3dlite_material_031_lights;
extern Lights0 logo_f3dlite_material_008_lights;
extern Lights0 logo_f3dlite_material_020_lights;
extern Lights0 logo_f3dlite_material_030_lights;
extern Lights0 logo_f3dlite_material_025_lights;
extern Lights0 logo_f3dlite_material_009_lights;
extern Lights0 logo_f3dlite_material_011_lights;
extern Lights0 logo_f3dlite_material_007_lights;
extern Lights0 logo_f3dlite_material_010_lights;
extern Lights0 logo_f3dlite_material_002_lights;
extern Lights0 logo_f3dlite_material_003_lights;
extern Lights0 logo_f3dlite_material_001_lights;
extern Lights0 logo_f3dlite_material_039_lights;
extern Lights0 logo_f3dlite_material_lights;
extern Lights0 logo_f3dlite_material_040_lights;
extern Lights0 logo_f3dlite_material_014_lights;
extern Lights0 logo_f3dlite_material_013_lights;
extern Lights0 logo_f3dlite_material_023_lights;
extern Lights0 logo_f3dlite_material_033_lights;
extern Lights0 logo_f3dlite_material_032_lights;
extern Lights0 logo_f3dlite_material_024_lights;
extern Lights0 logo_f3dlite_material_019_lights;
extern Lights0 logo_f3dlite_material_026_lights;
extern Lights0 logo_f3dlite_material_006_lights;
extern Lights0 logo_f3dlite_material_027_lights;
extern Lights0 logo_f3dlite_material_004_lights;
extern Lights0 logo_f3dlite_material_029_lights;
extern Lights0 logo_f3dlite_material_028_lights;
extern u8 logo_material_1_ci8[];
extern u8 logo_material_1_pal_rgba16[];
extern Vtx logo_Logo_mesh_vtx_0[84];
extern Gfx logo_Logo_mesh_tri_0[];
extern Vtx logo_Logo_mesh_vtx_1[3532];
extern Gfx logo_Logo_mesh_tri_1[];
extern Vtx logo_Logo_mesh_vtx_2[48];
extern Gfx logo_Logo_mesh_tri_2[];
extern Vtx logo_Logo_mesh_vtx_3[48];
extern Gfx logo_Logo_mesh_tri_3[];
extern Vtx logo_Logo_mesh_vtx_4[113];
extern Gfx logo_Logo_mesh_tri_4[];
extern Vtx logo_Logo_mesh_vtx_5[192];
extern Gfx logo_Logo_mesh_tri_5[];
extern Vtx logo_Logo_mesh_vtx_6[48];
extern Gfx logo_Logo_mesh_tri_6[];
extern Vtx logo_Logo_mesh_vtx_7[114];
extern Gfx logo_Logo_mesh_tri_7[];
extern Vtx logo_Logo_mesh_vtx_8[48];
extern Gfx logo_Logo_mesh_tri_8[];
extern Vtx logo_Logo_mesh_vtx_9[66];
extern Gfx logo_Logo_mesh_tri_9[];
extern Vtx logo_Logo_mesh_vtx_10[156];
extern Gfx logo_Logo_mesh_tri_10[];
extern Vtx logo_Logo_mesh_vtx_11[108];
extern Gfx logo_Logo_mesh_tri_11[];
extern Vtx logo_Logo_mesh_vtx_12[84];
extern Gfx logo_Logo_mesh_tri_12[];
extern Vtx logo_Logo_mesh_vtx_13[108];
extern Gfx logo_Logo_mesh_tri_13[];
extern Vtx logo_Logo_mesh_vtx_14[72];
extern Gfx logo_Logo_mesh_tri_14[];
extern Vtx logo_Logo_mesh_vtx_15[102];
extern Gfx logo_Logo_mesh_tri_15[];
extern Vtx logo_Logo_mesh_vtx_16[114];
extern Gfx logo_Logo_mesh_tri_16[];
extern Vtx logo_Logo_mesh_vtx_17[144];
extern Gfx logo_Logo_mesh_tri_17[];
extern Vtx logo_Logo_mesh_vtx_18[34];
extern Gfx logo_Logo_mesh_tri_18[];
extern Vtx logo_Logo_mesh_vtx_19[336];
extern Gfx logo_Logo_mesh_tri_19[];
extern Vtx logo_Logo_mesh_vtx_20[124];
extern Gfx logo_Logo_mesh_tri_20[];
extern Vtx logo_Logo_mesh_vtx_21[240];
extern Gfx logo_Logo_mesh_tri_21[];
extern Vtx logo_Logo_mesh_vtx_22[84];
extern Gfx logo_Logo_mesh_tri_22[];
extern Vtx logo_Logo_mesh_vtx_23[316];
extern Gfx logo_Logo_mesh_tri_23[];
extern Vtx logo_Logo_mesh_vtx_24[140];
extern Gfx logo_Logo_mesh_tri_24[];
extern Vtx logo_Logo_mesh_vtx_25[100];
extern Gfx logo_Logo_mesh_tri_25[];
extern Vtx logo_Logo_mesh_vtx_26[24];
extern Gfx logo_Logo_mesh_tri_26[];
extern Vtx logo_Logo_mesh_vtx_27[48];
extern Gfx logo_Logo_mesh_tri_27[];
extern Vtx logo_Logo_mesh_vtx_28[96];
extern Gfx logo_Logo_mesh_tri_28[];
extern Vtx logo_Logo_mesh_vtx_29[120];
extern Gfx logo_Logo_mesh_tri_29[];
extern Vtx logo_Logo_mesh_vtx_30[144];
extern Gfx logo_Logo_mesh_tri_30[];
extern Vtx logo_Logo_mesh_vtx_31[120];
extern Gfx logo_Logo_mesh_tri_31[];
extern Vtx logo_Logo_mesh_vtx_32[42];
extern Gfx logo_Logo_mesh_tri_32[];
extern Vtx logo_Logo_mesh_vtx_33[144];
extern Gfx logo_Logo_mesh_tri_33[];
extern Vtx logo_Logo_mesh_vtx_34[42];
extern Gfx logo_Logo_mesh_tri_34[];
extern Vtx logo_Logo_mesh_vtx_35[72];
extern Gfx logo_Logo_mesh_tri_35[];
extern Vtx logo_Logo_mesh_vtx_36[78];
extern Gfx logo_Logo_mesh_tri_36[];
extern Vtx logo_Logo_mesh_vtx_37[56];
extern Gfx logo_Logo_mesh_tri_37[];
extern Vtx logo_Logo_mesh_vtx_38[60];
extern Gfx logo_Logo_mesh_tri_38[];
extern Vtx logo_Logo_mesh_vtx_39[48];
extern Gfx logo_Logo_mesh_tri_39[];
extern Gfx mat_logo_f3dlite_material_022[];
extern Gfx mat_logo_f3dlite_material_036[];
extern Gfx mat_revert_logo_f3dlite_material_036[];
extern Gfx mat_logo_f3dlite_material_018[];
extern Gfx mat_logo_f3dlite_material_017[];
extern Gfx mat_logo_f3dlite_material_038[];
extern Gfx mat_logo_f3dlite_material_034[];
extern Gfx mat_logo_f3dlite_material_016[];
extern Gfx mat_logo_f3dlite_material_012[];
extern Gfx mat_logo_f3dlite_material_015[];
extern Gfx mat_logo_f3dlite_material_021[];
extern Gfx mat_logo_f3dlite_material_035[];
extern Gfx mat_logo_f3dlite_material_005[];
extern Gfx mat_logo_f3dlite_material_031[];
extern Gfx mat_logo_f3dlite_material_008[];
extern Gfx mat_logo_f3dlite_material_020[];
extern Gfx mat_logo_f3dlite_material_030[];
extern Gfx mat_logo_f3dlite_material_025[];
extern Gfx mat_logo_f3dlite_material_009[];
extern Gfx mat_logo_f3dlite_material_011[];
extern Gfx mat_logo_f3dlite_material_007[];
extern Gfx mat_logo_f3dlite_material_010[];
extern Gfx mat_logo_f3dlite_material_002[];
extern Gfx mat_logo_f3dlite_material_003[];
extern Gfx mat_logo_f3dlite_material_001[];
extern Gfx mat_logo_f3dlite_material_039[];
extern Gfx mat_logo_f3dlite_material[];
extern Gfx mat_logo_f3dlite_material_040[];
extern Gfx mat_logo_f3dlite_material_014[];
extern Gfx mat_logo_f3dlite_material_013[];
extern Gfx mat_logo_f3dlite_material_023[];
extern Gfx mat_logo_f3dlite_material_033[];
extern Gfx mat_logo_f3dlite_material_032[];
extern Gfx mat_logo_f3dlite_material_024[];
extern Gfx mat_logo_f3dlite_material_019[];
extern Gfx mat_logo_f3dlite_material_026[];
extern Gfx mat_logo_f3dlite_material_006[];
extern Gfx mat_logo_f3dlite_material_027[];
extern Gfx mat_logo_f3dlite_material_004[];
extern Gfx mat_logo_f3dlite_material_029[];
extern Gfx mat_logo_f3dlite_material_028[];
extern Gfx logo_Logo_mesh[];

extern const Gfx intro_seg7_dl_0700C6A0[];
extern const f32 intro_seg7_table_0700C790[];
extern const f32 intro_seg7_table_0700C880[];

// script
extern const LevelScript level_intro_splash_screen[];
extern const LevelScript level_intro_mario_head_regular[];
extern const LevelScript level_intro_mario_head_dizzy[];
extern const LevelScript level_intro_entry_4[];
extern const LevelScript script_intro_L1[];
extern const LevelScript script_intro_L2[];
extern const LevelScript script_intro_L3[];
extern const LevelScript script_intro_L4[];
extern const LevelScript script_intro_L5[];

#endif
